fn main() {
    // Stage 13: release builds inject the production license signing key(s)
    // at packaging time via `PIXORA_LICENSE_PUBKEYS` — a comma-separated
    // list of hex Ed25519 public keys. Public keys are safe to embed (they
    // verify licenses, they can never issue them); the private half lives
    // only in vendor tooling. An unset env var means a dev build: the
    // embedded dev key is the only verifier (see services/license/keys.rs).
    let injected: Vec<String> = std::env::var("PIXORA_LICENSE_PUBKEYS")
        .unwrap_or_default()
        .split(',')
        .map(|s| s.trim().to_ascii_lowercase())
        .filter(|s| !s.is_empty())
        .collect();
    for key in &injected {
        assert!(
            key.len() == 64 && key.chars().all(|c| c.is_ascii_hexdigit()),
            "PIXORA_LICENSE_PUBKEYS entries must be 64-char hex public keys"
        );
    }
    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let body: String = injected.iter().map(|k| format!("\"{k}\",")).collect();
    std::fs::write(
        out_dir.join("license_pubkeys.rs"),
        format!("// generated by build.rs — production license public keys\npub const INJECTED: &[&str] = &[{body}];\n"),
    )
    .expect("write injected license keys");
    println!("cargo:rerun-if-env-changed=PIXORA_LICENSE_PUBKEYS");

    // Refuses the app at build time when capabilities/permissions are misconfigured.
    tauri_build::build()
}
