fn main() {
    // Stage 13: release builds inject the production license signing key(s)
    // at packaging time via `FOVEA_LICENSE_PUBKEYS` — a comma-separated
    // list of hex Ed25519 public keys. Public keys are safe to embed (they
    // verify licenses, they can never issue them); the private half lives
    // only in vendor tooling. An unset env var means a dev build: the
    // embedded dev key is the only verifier (see services/license/keys.rs).
    let injected: Vec<String> = std::env::var("FOVEA_LICENSE_PUBKEYS")
        .unwrap_or_default()
        .split(',')
        .map(|s| s.trim().to_ascii_lowercase())
        .filter(|s| !s.is_empty())
        .collect();
    for key in &injected {
        assert!(
            key.len() == 64 && key.chars().all(|c| c.is_ascii_hexdigit()),
            "FOVEA_LICENSE_PUBKEYS entries must be 64-char hex public keys",
        );
    }
    // A release binary with no verifier can never activate a license: every
    // customer who buys would be stuck on "this key isn't recognised", and
    // nothing at runtime would tell them the build is at fault. Fail loudly
    // at packaging time instead.
    if std::env::var("PROFILE").as_deref() == Ok("release") && injected.is_empty() {
        panic!(
            "release build has no license public key. Issue or reuse a signing \
             keypair (`cargo run --example issue_license -- --generate`) and \
             rebuild with FOVEA_LICENSE_PUBKEYS=\"<hex public key>\""
        );
    }
    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let body: String = injected.iter().map(|k| format!("\"{k}\",")).collect();
    std::fs::write(
        out_dir.join("license_pubkeys.rs"),
        format!("// generated by build.rs — production license public keys\npub const INJECTED: &[&str] = &[{body}];\n"),
    )
    .expect("write injected license keys");
    println!("cargo:rerun-if-env-changed=FOVEA_LICENSE_PUBKEYS");

    // Stage 20 packaging: the plan this installer was *branded* for.
    // `scripts/build-tiers.mjs` sets it per tier so a Fovea Pro build knows it
    // is a Fovea Pro build — which is what lets the app name itself correctly
    // and tell a buyer whose key has not been pasted yet what they are missing.
    // It never grants anything: the license record stays the only authority
    // over entitlements. No marker = the free build, and every `tauri dev`.
    let build_plan = match std::env::var("FOVEA_BUILD_PLAN")
        .unwrap_or_default()
        .trim()
        .to_ascii_lowercase()
        .as_str()
    {
        "" | "free" => "free",
        "pro" => "pro",
        "studio" => "studio",
        other => panic!("FOVEA_BUILD_PLAN must be free, pro or studio — got {other:?}"),
    };
    std::fs::write(
        out_dir.join("build_plan.rs"),
        format!("// generated by build.rs — the plan this installer was branded for\npub const BUILD_PLAN: &str = \"{build_plan}\";\n"),
    )
    .expect("write build plan marker");
    println!("cargo:rerun-if-env-changed=FOVEA_BUILD_PLAN");

    // Refuses the app at build time when capabilities/permissions are misconfigured.
    tauri_build::build()
}
