//! Tauri commands: the complete native API surface exposed to the UI.
//!
//! Rules for this layer:
//! - Validate and forward only. Logic lives in `services`.
//! - Return `AppResult<T>` so errors reach the UI as `{ code, message }`.
//! - Never return raw internal error text.
//!
//! `generate_handler!` references these paths directly (the macro relies on
//! companion items generated by `#[tauri::command]` inside each module).

pub mod app;
